DROP TABLE IF EXISTS meals;

CREATE TABLE meals(
    meal_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id integer REFERENCES users(id)ON DELETE CASCADE,
	local_date_time TIMESTAMP,
	description varchar(50)not null,
	calories int not null
);
